=== 02cx/dong-rpc/drpc-framework/drpc-core/src/main/java/com/dong/builder/xml/drpc-config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--        <!ELEMENT configuration ( port?,
                applicationName?, register?,
                serializeType?, serialize?,
                compressorType?, compressor?,
                loadBalanceType?, loadBalance?,
                idGenerator?
                )>-->

        <!ELEMENT configuration ANY)>

        <!ELEMENT port ANY>

        <!ELEMENT applicationName ANY>

        <!ELEMENT register EMPTY>
        <!ATTLIST register
                url CDATA #REQUIRED
                >

        <!ELEMENT serializeType EMPTY>
        <!ATTLIST serializeType
                type CDATA #REQUIRED
                >

        <!ELEMENT serialize EMPTY>
        <!ATTLIST serialize
                class CDATA #REQUIRED
                >

        <!ELEMENT compressorType EMPTY>
        <!ATTLIST compressorType
                type CDATA #REQUIRED
                >

        <!ELEMENT compressor EMPTY>
        <!ATTLIST compressor
                class CDATA #REQUIRED
                >

        <!ELEMENT loadBalanceType EMPTY>
        <!ATTLIST loadBalanceType
                type CDATA #REQUIRED
                >

        <!ELEMENT loadBalance EMPTY>
        <!ATTLIST loadBalance
                class CDATA #REQUIRED
                >

        <!ELEMENT idGenerator EMPTY>
        <!ATTLIST idGenerator
                class CDATA #REQUIRED
                dataCenterId CDATA #REQUIRED
                machineId CDATA #REQUIRED
                >

=== 02cx/dong-rpc/drpc-framework/drpc-core/src/main/resources/drpc-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "http://dong.com/drpc-config.dtd">
<configuration>

    <port>8010</port>
    <applicationName>drpc-default-name</applicationName>
    <register url="zookeeper://192.168.183.130:2181"/>

    <serialize class="com.dong.serialize.impl.HessianSerializer"/>
    <compressorType type="gzip"/>

    <idGenerator class="com.dong.IdGenerator" dataCenterId="2" machineId="2"/>

    <loadBalance class="com.dong.loadbalance.impl.RoundRobinLoadBalance"/>

</configuration>
